name: app
description: "Fitness Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: any
  isar: any
  isar_flutter_libs: any
  logger: ^2.4.0
  path_provider: ^2.1.4
  phone_form_field: ^9.2.8

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Janna
      fonts:
        - asset: fonts/Janna-lt-reg.ttf
          weight: 400
        - asset: fonts/Janna-lt-bold.ttf
          weight: 700
